### ISSUE TITLE
Compatibility question

### ISSUE THREAD

**Issue by arbox** [red-data-tools/red-arrow#1]
Just a small question about the plans/compatibility state with the Feather project: https://github.com/wesm/feather

**Comment by kou** [comment]
It's supported when apache/arrow#699 is merged. (It'll be merged soon.)

**Comment by arbox** [comment]
Very good news! Then we can advertise for that in the community! 
I'll put your project on our RubyDataScience list: https://github.com/arbox/data-science-with-ruby

**Comment by kou** [comment]
OK.
