### ISSUE TITLE
Interest in donating to Apache Arrow?

### ISSUE THREAD

**Issue by wesm** [red-data-tools/red-arrow#7]
hi @kou -- I wondered if you would like to promote this work to be the official Ruby library for Apache Arrow? I am not sure if it would help with Arrow community development.

**Comment by kou** [comment]
Ah, OK. I'll do it until the next Apache Arrow release. Please wait.
Does this library need IP clearance check like Apache Arrow Go? Most of this library are written by me  https://github.com/red-data-tools/red-arrow/graphs/contributors and licensed under Apache License 2.0.
If it's needed, I may need to work harry for the next Apache Arrow.

**Comment by wesm** [comment]
Yes, we would want to do an IP clearance since the codebase has been around for a while. It should not be too painful

**Comment by kou** [comment]
OK. I'll work on this.

**Comment by kou** [comment]
Done: apache/arrow#1990
